---
title: "Welcome and a Little about Me"
author: "Vincent Tam"
date: "November 1, 2018"
output: html_document
---
---
title: "Habits"
output:
  html_document:
    toc: true
    toc_depth: 2
---
I am by no means a data scientist but am simply an MS Toxicology student expanding his skill set to obtain a better grasp of the knowledge out there. As a message for future neophytes learning to master the language of R, don't despair. The tools are here for learning. Simply keep trying and practice.  

You might be wondering about the webpage title, "The Accidental Lover of a Data Scientist". To tell you the truth, I was on the fence about learning programming since it is a time-consuming endeavour for a busy Columbia student. Although R is a much-coveted skill, it was the desire to grow closer and better understand the frustrations of a distractingly cute, budding data scientist/biostatistics student that sealed the deal for me. I am terrible at conveying feelings and R might help me express the words of love that so easily escape me. So the language of R in this case, is partially a love story of boy chasing girl, but awkwardly doing it, in his stumbling and accidental ways. Happy ending? All I can say, it's like me learning how to program, there's a steep learning curve. We'll have to find out my grade at the end of the semester!  

Although passionate about science, I believe that scientists should be well-rounded individuals that can appreciate other aspects of life. I have always admired writers, painters, and other creative artists that can inspire and easily communicate their message to the masses. I minored in East Asian Studies and developed a small taste for the beauty of Chinese poems, not only for the aesthetics of the written characters but also for the expert use of words and phrasing. My choice in poems stem from my experiences and how relatable the pieces are to my life. "Life Imitates Art and Art Imitates Life", they give me comfort in knowing that I am not alone in my despairs and will see myself through them. For a further practical standpoint, reading poetry has improved my humble Chinese vocabulary immensely. So, please feel free to enjoy a sampling of Chinese poems for philisophical and educational purposes.   
  
邶風擊鼓              |  North Wind and Beating Drums (rough translation)
--------------------- | -------------
擊鼓其鏜，踴躍用兵。  |
土國城漕，我獨南行。  | xyz
從孙子仲，平陳與宋。  |    | Content Cell
不我以歸，憂心有忡。  |
爰居爰處，爰喪其馬，  |
于以求之，于林之下。  |
死生契闊，與子成說。  |
執子之手，與子偕老。  |
于嗟阔兮，不我活兮。  |
于嗟洵兮，不我信兮。  |  


君生我未生              |  I Was Not When You Were Born
------------------------|--------------------------------
君生我未生，我生君已老。|  
君恨我生遲，我恨君生早。|  test
君生我未生，我生君已老。|  
恨不生同時，日日與君好。|  
我生君未生，君生我已老。|  
我離君天涯，君隔我海角。|  
我生君未生，君生我已老。|  
化蝶去尋花，夜夜棲芳草。|