---
title: "Resume"
---
## Vincent Tam  
### Education  
Columbia University, Mailman School of Public Health, New York, NY Expected Graduation Oct 2019
MS in Environmental Toxicology, GPA 3.8/4.0
Columbia University, School of General Studies, New York, NY May 2017 Bachelor of Arts, Biology, GPA 3.6/4.0
Dean’s List: 4 Semesters

### Professional Experience  
Air Pollution Research Assistant June 2018 - Present
Columbia University Mailman School of Public Health, New York, NY
 Installed equipment to gather data relevant to environmental pollution in NYC neighborhoods
 Analyzed collected data to interpret results and effects on the human population
Part-Time Hospital Assistant and Veterinary Tech Assistant April 2016 – Present
Bronx Zoo Wildlife Heath Center, New York, NY
 Responsible for efficient daily care of patients that can number over 200 individuals at any given time
 Practice quarantine protocols to control spread of infections including zoonotic diseases
 Maintain meticulous daily records of patient feedings, medications, and activities
Teaching Assistant for Certificate Program in Conservation & Environmental Sustainability March 2013 – Present
Columbia University Earth Institute for Environmental Sustainability, New York, NY
 Assists an average of three professors per week in managing course content and administrative tasks
 Aids five to seven students per course in navigating course work and understanding key concepts
Teaching Assistant for Master’s in Public Administration in Environmental Science and Policy May 2018 – Aug 2018
Columbia University School of International and Public Affairs, New York, NY
 Assisted in Environmental Chemistry and Risk Assessment & Toxicology courses
 Conducted office hours that taught and reinforced key concepts and skills
Ornithology Fellow and Volunteer May 2014 – April 2016
Bronx Zoo Ornithology Department, New York, NY
 Conducted husbandry duties and maintenance for the safety and comfort of birds numbering in the hundreds
 Led information talks with visitors about the importance of avian conservation and protection of environment to humans

### Activities
NY Strangers Sports Association April 2010 - Present
 Serving as a volleyball coach and mentor to children while leading the organization in community-service events
Equity Trading and Investing May 2011 - Present
 Developed daily, weekly, and monthly plans for trading equities with a combination of fundamental and technical analysis
American Association of Zookeepers (New York City AAZK Chapter) Jan 2017 – Present
 Member and participant in a variety of AAZK events that educate and raise money for the sake of conservation awareness
Honeybee Conservancy January 2018 - Present
 Authoring researched fact sheets for public distribution about incorporating honeybees in the NYC urban environment
Honeybee Bio-Indicator Research May 2018 - Present
 Researching feasibility of domestic apiaries in an urban setting as indicators of environmental toxins
Columbia University Clubs and Organizations Jan 2013 – Present
 Financial Engineering, One Health Initiative, Pre-Vet, Consulting, Archery
### Languages and Skills  
Languages
 English (Native Proficiency); Cantonese (Limited Working Proficiency); Mandarin (Limited Working Proficiency)
Computer Skills
 Geographic Information System (GIS), Microsoft Office Suite, R Computer Language
Research Skills
 Spectroscopy (UV-VIS, GFAAS, Flame Emission); Chromatography; ELISA; PCR; Immunostaining, Fecal Flotation, Blood Smear, Air Sample Collection, Surface Contamination Swab, Air Monitoring Methods, Hazardous Waste Operations and Emergency Response Certified